name: Deploy to EC2
on: 
  push: 
    branches: 
      - main 

jobs: 
  deploy:
    runs-on: ubuntu-latest  
    steps: 
      - name: 🚀 Starting Deployment
        run: echo "Deployment started..."

      - name: 📥 Checkout Code
        uses: actions/checkout@v3
      - name: 🔐 Connecting to EC2 & Deploying
        uses: appleboy/ssh-action@v1.0.3
        with:
            host: ${{ secrets.EC2_HOST }}
            username: ${{ secrets.EC2_USER }}
            key: ${{ secrets.EC2_SSH_KEY }}
            debug: true
            script: |
              echo "✅ Connected to EC2"

              echo "📂 Moving to project directory..."
              cd /home/ubuntu/aws

              echo "⚙️ Loading environment..."
              export NVM_DIR="$HOME/.nvm"
              [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

              echo "Node version:"
              node -v || echo "❌ Node not found"

              echo "NPM version:"
              npm -v || echo "❌ NPM not found"

              echo "PM2 version:"
              pm2 -v || echo "❌ PM2 not found"

              echo "🔄 Pulling latest code..."
              git pull origin main

              echo "📦 Installing dependencies..."
              npm install

              echo "🔁 Restarting app..."
              pm2 restart cicd

              echo "🎉 Deployment done!"


        
